baseurl = "http://docs.ernest.io/"
languageCode = "en-us"
title = "Ernest"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-86033085-1"

[params]
	# General information
	author      = "Ernestio"
	description = "Developer Driven Orchestration"
	copyright   = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/ernestio/ernest"

	version = "3.4.0"
	logo    = "images/dog.png"
	favicon = "images/dog.ico"

	permalink = "#"

	# Custom assets
	custom_css = [
	  "forms.css"
	]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light-blue"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "R3Labs"
	github  = "ernestio"
	email   = "info@r3labs.io"


[[menu.main]]
	name   = "Ernest"
	url    = "/"
	weight = 5

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Commands (CLI)"
	url    = "commands/"
	weight = 15

[[menu.main]]
	name   = "Providers"
	url    = "providers/"
	weight = 16

[[menu.main]]
	name   = "Downloads"
	url    = "downloads/"
	weight = 30

[[menu.main]]
	name   = "Developer"
	url    = "developer/"
	weight = 40

[[menu.main]]
	name   = "Community"
	url    = "community/"
	weight = 50

[[menu.main]]
	name   = "Support"
	url    = "support/"
	weight = 60

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 70

[blackfriday]
	smartypants    = true
	fractions      = true
	smartDashes    = true
	plainIDAnchors = true
